# -*- coding: utf-8 -*-
"""
Created on Mon Aug  1 12:06:45 2016

@author: guillermo
"""

def Match(seq, pattern):
    winlen = len(pattern)
    for i in xrange(len(seq)):
        if pattern == seq[i:i+winlen]:
            print i+1
    return


if __name__ == '__main__':
    seq = "TGTCATGCGTGGACTGGGTCATGCGCACTCATGCGCTATCATGCGTTCATGCGGCTCATGCGAAATCCCTTCATGCGACTATTCATGCGCTCATGCGTGTATTCATGCGTATCATGCGATCATGCGTTCAGCTCATGCGACGCACTCATGCGTCATTCTAGCAGCTATCATGCGCTCATGCGCCCATCATGCGGACATCATGCGTTCATGCGTCATGCGGGCCTCTCATGCGCGTCTCATGCGTCATGCGCACCGATCATGCGGGAGTGATCATGCGCAGCGATGAGGGAATCGACATCATGCGTCATGCGGGGTCATGCGAAGTCATGCGGTCACGGAGCCGTCATGCGTGTGTCATGCGTTCATGCGTGTCATGCGCAGTTCATGCGTCATGCGGCTCATGCGCACTCATGCGGTAATTCATGCGTATCATGCGGGGTCATGCGCACGGTCATGCGGACTCATGCGGTGTTCATGCGCGGCTCATGCGTCATGCGGCCGTCGTCATGCGTCATGCGATTTCGTTCATGCGTCATGCGTCTAGAGTATACTAGATCATGCGTCATGCGCCTCATGCGACAATGGTTCATGCGTTCATGCGGAATCATGCGATCATGCGTCATGCGCGTCTCATGCGCTCATGCGTAAACTTCATGCGTCATGCGATTTCATGCGCATCATGCGCTCTCATGCGTCATGCGGTCATGCGATCATGCGACGTCATGCGGGCCCTCATGCGTCATGCGTCATGCGTTCATGCGTTCATGCGACTTCATGCGAGTGATCATGCGGTCATGCGTATCATGCGTCAATCATGCG"
    pattern = "TCATGCGTC"
    Match(seq, pattern)